apiVersion: batch/v1
kind: Job
metadata:
  name: my-contacts
spec:
  template:
    metadata:
      name: my-contacts-pod
    spec:
      containers:
      - name: my-contacts
        image: my-contacts
        imagePullPolicy: Never
      restartPolicy: Never
