apiVersion: v1
kind: Pod
metadata:
  name: my-contacts-pod
  labels:
    app.kubernetes.io/name: "MyContacts"
spec:
  containers:
  - name: my-contacts
    image: tutum/hello-world
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never
